"""rename address

Revision ID: e8b08fb21373
Revises: d9522261a51a
Create Date: 2025-06-20 19:17:16.533122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b08fb21373'
down_revision = 'd9522261a51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    op.rename_table('employee', 'employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    op.rename_table('employees', 'employee')
    # ### end Alembic commands ###
